public with sharing class SolarCaseRequestWrapper 
{
	public String idCliente;
	public String idContrato;
	public String contractNumber;
	public String operatorCode;
	public String tipoAtendimento;
	public String servico;
	public String motivo;
	public String subMotivo;
	public String categoria;
	public String subCategoria;
	public String canal;
	public String origem;
	public String fluxo;
    public String motivoContato;
	public String protocolo; 
    public String modalidadeServico;
	public String contactMobile;			
	public String idFatura;
	public String motivoEntrada;
	public String motivoSaida;
	public String motivoEncaminhamento;
	public String descricaoSolicitacao;
	public String status;
    //public String alcada; bia
}