/**
 * @description       :
 * @author            : Joao Neves
 * @group             :
 * @last modified on  : 19-01-2021
 * @last modified by  : Joao Neves
 * Modifications Log
 * Ver   Date         Author       Modification
 * 1.0   19-01-2021   Joao Neves   Initial Version
 **/
public class FinancialNegotiationEfetivationWrapper {
	//internos
	public Boolean hasAuthority;
	public String operatorCode;
	public String contractNumber;
	public String userName;
	public String amount;
	public String amountTela;
	public String partnerId;
	public String functionalityRuleId;
	public String billId;
	public String itemGroupId;
}
