public class InvoiceRefundWrapper {
 @AuraEnabled
    public String titular{get;set;}
 @AuraEnabled
    public String refundType{get;set;}    
 @AuraEnabled
    public String nomeTitular{get;set;}
 @AuraEnabled
    public String cpf{get;set;}
 @AuraEnabled
    public String cnpj{get;set;}
 @AuraEnabled
    public String banco{get;set;}
 @AuraEnabled
    public Integer agencia{get;set;}
 @AuraEnabled
    public Integer conta{get;set;}
 @AuraEnabled
    public Integer digito{get;set;}
 @AuraEnabled
    public String motivoReemb{get;set;}
 @AuraEnabled
    public String reembDobro{get;set;}
 @AuraEnabled
    public String descricao{get;set;}
 @AuraEnabled
    public String pessoa{get;set;}
 @AuraEnabled
    public String email{get;set;}
 @AuraEnabled
    public Date vencimentoFatura{get;set;}
 @AuraEnabled
    public String tel1{get;set;}
 @AuraEnabled
    public String tel2{get;set;}
    
}